version: "3"
services:
  nchs-mallet-api:
    build: .
    #command: "uvicorn api:app"
    #command: "python -m pip --version"
    #command: "pip3 --version"
    command: "uvicorn api:app --host 0.0.0.0"

    ports:
      - "8000:8000"
    
    #volumes:
    #  - "./src:/usr/src/app/src"